-- niches_whyitworks.sql
-- Adds "Why this works" content to each niche's collapsible section.
-- Idempotent — safe to re-run. Updates why_it_works only, leaves other fields untouched.
-- Apply with: psql "$DATABASE_URL" -f niches_whyitworks.sql
-- Or via: ./seed-niches.sh (after merging into seed file)

UPDATE niches SET "why_it_works" = E'62% of HVAC customer calls come outside traditional 9-to-5 hours, and 85% of callers who reach voicemail won''t leave a message. During peak summer, call volume spikes roughly 340% and miss rates hit 71% — concentrated in an 8-week window that drives about a third of annual revenue.\n\nThe sale is won by the first live answer, not the best pitch. An owner in a crawlspace can''t pick up, and the homeowner who got voicemail has already called the next contractor by the time you call back.\n\nThat''s why a free after-hours answering script beats any sales pitch. It solves the problem you live with every July — leads evaporating because nobody answered. Hand it to your dispatcher or after-hours service tonight, and the next burst of emergency calls gets captured instead of lost. No consultancy fee, no demo, no "let''s schedule a discovery call." Just a working script you can use before the next heatwave.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'hvac';

UPDATE niches SET "why_it_works" = E'About 47% of home service inquiries come after standard hours, and 80% of callers who reach voicemail hang up without leaving a message. Plumbers miss roughly 28% of inbound calls on average — not because they''re ignoring the phone, but because they''re elbow-deep in a job and physically can''t answer.\n\nA burst pipe at 9pm doesn''t wait. The homeowner with water on the kitchen floor calls the next plumber on the Google list, not the one who promised to call back. Average emergency call value runs $400–600, and each missed call is that money walking to a competitor.\n\nA free emergency intake script fixes the one thing you actually control: what happens when the call connects. It captures urgency, address, and a callback number every time, so even if you''re under a sink when the phone rings, the lead isn''t lost. No pitch, no retainer — just a script your dispatcher or answering service can use tonight.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'plumbing';

UPDATE niches SET "why_it_works" = E'The average dental practice loses 12–18% of appointments to no-shows and same-day cancellations. New-patient appointments carry the highest risk — 25–30% no-show rate — and a 400-patient practice at 15% no-show loses $4,500–$6,250 every month in chair time that can''t be resold.\n\nPatients who miss and aren''t proactively rebooked have a 40% higher 12-month lapse rate. They don''t return on their own. Yet most front desks aren''t trained on call handling as a conversion skill — they''re trained on insurance verification and scheduling software.\n\nThat''s why a free new-patient call script outperforms any marketing pitch. It gives your front desk the 7 questions that turn an inquiry call into a booked appointment, and the reminder cadence that cuts no-shows from 15% to under 8%. Practices using structured multi-touchpoint recall consistently recover $48K–$66K/year. You don''t need a marketing agency — you need your existing phones answered better.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'dental';

UPDATE niches SET "why_it_works" = E'39% of agent leads now come through social media, 23% through CRM, and only 17% through the MLS — but only 38% of agents say their brokerage provides the tech tools they actually need. Agents self-fund $50–$250/month out of pocket chasing leads that mostly go cold.\n\nHere''s the hard truth: sellers interview multiple agents and pick based on perceived hustle. The first agent to respond with a real conversation wins. A cold pitch to a homeowner doesn''t overcome the relational advantage of the agent who answered instantly and demonstrated local knowledge.\n\nThat''s why a free listing-acquisition script beats any lead-gen tool. It''s built around the value-first call — bringing the seller a local benchmark report on what the top 10% of agents in their suburb do differently, before asking for the listing. It''s the same approach that wins listings in competitive farm areas: show up with insight, not a pitch.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'realestate';

UPDATE niches SET "why_it_works" = E'Insurance brokers lose accounts at renewal because policyholders shop rates 30 days before the renewal date — and most brokers don''t call until the renewal notice arrives, which is too late. By then the client has already compared quotes online and half-decided.\n\nThe brokers who retain 90%+ don''t wait for the renewal notice. They call 60 days out with a coverage review — not a sales pitch, but an actual audit of whether the client is still properly covered given changes in their life, assets, or risk exposure. That call does two things: it surfaces gaps the online quote comparison won''t catch, and it reminds the client why they use a broker instead of a website.\n\nA free renewal retention script gives your team the 5 touchpoints that cut churn by 15%: the pre-renewal review call, the coverage-gap email, the bundling check-in, the claim-history recap, and the birthday call. None of them ask for the sale. All of them make leaving feel like a mistake.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'insurance';

UPDATE niches SET "why_it_works" = E'Every missed call in legal intake costs $500–$2,000+ — the highest per-call loss of any service industry. PI, family, and criminal intakes are time-sensitive by nature: a claimant who reaches voicemail at 7pm calls the next firm on the list before you open at 9am.\n\nLawyers are rightly skeptical of marketing agencies because of ethics rules around solicitation. A cold pitch reads as spam to someone who''s spent a decade building a referral reputation. But every firm — even the most referral-driven — has an intake leak: calls that come in after hours, during depositions, or when the paralegal is on another line. Those calls don''t leave voicemails. They call the next name on Google.\n\nA free intake call script solves the problem without touching your ethics position. It gives your intake staff the questions that turn a 90-second inquiry call into a booked consultation with a 40%+ show rate. No marketing, no solicitation — just intake training your staff can use today. The firm that answers and books wins the case. The firm that doesn''t never knows it lost one.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'legal';

UPDATE niches SET "why_it_works" = E'After a storm, the first roofer to reach the homeowner wins — but storm-chasing cold door-knocks have poisoned the channel. Homeowners distrust unsolicited roofers because they''ve been burned by out-of-town crews who take deposits and disappear. The industry miss rate during peak demand runs 55–65%, and the average missed storm call costs $1,000+ in lost job value.\n\nThe roofers who win storm season don''t knock doors. They answer phones fast, document damage thoroughly, and help the homeowner navigate the insurance claim — which is the part homeowners are most scared of. A roofer who shows up with a damage report template and a claim-filing checklist isn''t selling; they''re rescuing.\n\nA free storm-response call script gives your team the intake questions that capture urgency and address info every time, plus the insurance-claim language that builds trust in the first 60 seconds. The contractor who answers live, documents properly, and speaks the claim process fluently gets the job. The one who cold-knocks gets the door closed.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'roofing';

UPDATE niches SET "why_it_works" = E'54% of solar salespeople report competition increased in their market this year, and 30% call it "much more competitive." The 2026 Aurora Solar industry snapshot concluded that trust is now the decisive variable — reps who lead with education and transparency outperform those who lead with price cuts and financing tricks.\n\nHomeowners are wary of high-pressure solar sales. They''ve been door-knocked by five companies, quoted conflicting savings numbers, and burned by installers who disappeared after the PTO. The slick pitch doesn''t work anymore. What works is showing up before the sales appointment with something useful — a custom savings analysis, a local installer comparison, or a rebate-eligibility check the homeowner didn''t know they qualified for.\n\nA free appointment-confirmation script does exactly that. It cuts no-shows by delivering value before the rep arrives: the homeowner gets a real reason to keep the appointment beyond "someone is coming to sell you panels." In a market where trust wins, the script that builds trust before the close is worth more than any lead list.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'solar';

UPDATE niches SET "why_it_works" = E'Mortgage leads shop multiple lenders simultaneously. The first loan officer to return a Loan Estimate with a clear number wins — not the one with the lowest rate on a landing page, but the one who calls back fastest with a real figure the borrower can compare.\n\nThe problem isn''t lead volume. LOs are bombarded with lead-gen pitches, but more leads don''t help if the response time is 4 hours instead of 5 minutes. A lead that sits overnight has already applied with someone else. The economics are brutal: qualifying a lead within 5 minutes makes you 21x more likely to convert than waiting 30 minutes, yet most LOs don''t have a system for that.\n\nA free lead-gen call script fixes the two things that actually matter: speed and substance. It gives you the pre-qualification questions that turn a rate-shopper into a pre-approval in one call, and the follow-up cadence that keeps past clients from forgetting who closed their last loan. You don''t need more leads — you need the calls you''re already getting to convert.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'mortgage';

UPDATE niches SET "why_it_works" = E'Medical spa consults have the same no-show problem as dental — 30%+ on booked aesthetic appointments — but with higher stakes. A medspa patient who no-shows a $500+ consultation might have booked a $5,000+ treatment package. One missed consult can cost more than a full day of chair time in a dental practice.\n\nMedspa owners are sensitive to "salesy" framing because aesthetic patients want results, not to be sold. The consult is supposed to feel like a clinical assessment, not a closing room. But front desks aren''t trained on consult-confirmation as a conversion skill — they send a reminder text and hope.\n\nA free consultation call script gives your team the 3 touchpoints that cut no-shows by 35%: the booking confirmation call (not text), the 48-hour value reminder (what they''ll learn at the consult, not just when it is), and the morning-of check-in. None of them pitch. All of them make the patient feel like the practice is prepared and professional — which is the exact feeling that makes them show up and proceed.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'medspa';

UPDATE niches SET "why_it_works" = E'Pest control runs on quarterly service contracts — steady recurring revenue until customers silently churn. They don''t cancel. They just stop paying, and nobody notices until the renewal has lapsed and the customer has signed up with the $99 newcomer special that showed up in their Facebook feed.\n\nOperators are constantly pitched "more leads" but that''s the wrong lever. Adding new customers while leaking existing ones is a treadmill — you work harder every quarter just to stay flat. The operators who grow have retention systems, not just lead-gen budgets. They call before the renewal with a service-value recap: what was treated, what was caught, what risks are coming next season. That call makes the customer feel like they have an account manager, not a subscription.\n\nA free renewal script gives your team the pre-renewal touchpoint that stops silent churn: a 5-minute call recapping the year of service and flagging the one pest risk the customer didn''t know about. It''s the difference between "just another bill" and "I''d be stupid to cancel this."', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'pest-control';

UPDATE niches SET "why_it_works" = E'Accountants win clients through referral, not lead-gen. Business owners choose advisors on trust — they want someone who understands their industry, not someone who ran a Facebook ad. A generic "we''ll get you clients" pitch contradicts how accounting practices actually grow, which is why most accountants ignore marketing agencies entirely.\n\nBut referral-only growth has a ceiling, and the firms that break through it do so by giving away expertise before asking for the engagement. They publish industry-specific tax-saving benchmarks. They host cash-flow workshops for a specific vertical — restaurants, trades, e-commerce. They produce the kind of analysis a business owner can''t get from QuickBooks, and they give it away to people who''ve never heard of them.\n\nA free client-acquisition script operationalizes that approach. It gives your team the three-call framework for reaching a prospect with genuine insight first — a benchmark report on what similar businesses in their industry are deducting — before ever mentioning your firm. It''s how advisory firms actually convert, structured into a script your staff can execute.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'accounting';

UPDATE niches SET "why_it_works" = E'Australia has one of the highest rooftop solar penetration rates in the world — over 30% of detached homes have panels. But demand is rebate-driven and lumpy. State rebate windows create lead floods followed by droughts, and installers who can''t capture and nurture leads through the rebate cycle lose them to whoever quotes the same STC discount fastest.\n\nAU solar leads are price-sensitive and time-pressured. A homeowner who qualifies for a state rebate has a narrow window to install before the scheme changes, and they''re getting quotes from 5+ installers in the same week. The installer who calls back within the hour with a rebate-aware quote wins. The one who takes 24 hours loses to someone who isn''t necessarily cheaper — just faster.\n\nA free lead-gen script built for the AU market gives your team the rebate-eligibility questions that turn a cold inquiry into a qualified quote in one call, plus the follow-up cadence that keeps the lead warm through the rebate paperwork. In a market where speed and rebate fluency win, the script that delivers both is worth more than another lead channel.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'solar-au';

UPDATE niches SET "why_it_works" = E'Australia has no MLS. Listings are won by the agent who secures the appraisal and converts it to an exclusive listing agreement — and the competition is intense, with 30+ agents competing per suburb in metro markets. The listing goes to the agent who shows up with the most local market intelligence, not the one with the lowest commission.\n\nAU sellers expect an appraisal meeting, not a cold call. They want to know what their home is worth, what the agent will do differently, and why they should sign an exclusive with one agent for 90 days. A generic pitch doesn''t survive that conversation. What does is showing up with a suburb-level benchmark — recent comparable sales, days-on-market data, and the specific pricing strategy the top 10% of agents in that suburb use.\n\nA free listing call script built for the AU market gives you the appraisal-call framework that wins exclusives: the local data you bring to the first meeting, the questions that surface the seller''s real motivation, and the listing-pitch that earns a 90-day exclusive without discounting your commission.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'realestate-au';

UPDATE niches SET "why_it_works" = E'Over 70% of Australian mortgages are now written through brokers — up from roughly 40% a decade ago. The broker channel dominates, which means competition among brokers for purchase and refi leads is fierce. In metro markets, a single borrower may be working with 3–5 brokers simultaneously, all quoting against each other.\n\nThe brokers who win aren''t the ones with the lowest rate — rates are visible on comparison sites and everyone matches them. The winners are the ones who return a pre-approval fastest and who maintain the relationship past settlement. AU borrowers forget their broker within months of settling — which means the next time they need a loan (refi, investment property, upgrade), they start fresh on a comparison site instead of calling the person who already has their financials.\n\nA free lead-gen script built for the AU broker market gives you the pre-qualification call that turns a rate-shopper into a pre-approval in one conversation, plus the post-settlement reactivation cadence that keeps past clients from forgetting you exist. You don''t need more leads — you need the ones you have to stick.', "updated_at" = CURRENT_TIMESTAMP WHERE "slug" = 'mortgage-au';