import Link from "next/link";

export default function TermsAndConditionsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-12">
      <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
        Terms &amp; Conditions
      </h1>
      <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
        Last updated: June 18, 2026
      </p>

      <div className="mt-8 space-y-6 text-sm text-zinc-700 dark:text-zinc-300">
        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">1. Acceptance of Terms</h2>
          <p className="mt-2">
            By accessing or using OfferFu (&quot;the Service&quot;), operated by SalesFu AI Pty Ltd, you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">2. Description of Service</h2>
          <p className="mt-2">
            OfferFu is a free value offer and outbound call script generator powered by artificial intelligence. The Service helps users craft value offers and three-call scripts for any vertical market. The Service is provided at no cost to users.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">3. Free Use</h2>
          <p className="mt-2">
            The Service is provided to you free of charge. You may generate value offers and outbound call scripts at no cost, subject to the tiered usage limits described on the Pricing page. We reserve the right to change, suspend, or discontinue the Service at any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">4. Account Registration</h2>
          <p className="mt-2">
            You may use the Service anonymously for a limited number of sessions. To save scripts, export content, or access higher-tier features, you must register an account by providing your email address. To unlock full access, you must also verify a phone number and consent to SMS communications.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">5. SMS Communications</h2>
          <p className="mt-2">
            When you add your phone number, you consent to receive text messages from OfferFu. These may include:
          </p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li>Verification codes for account security</li>
            <li>Notifications about your generated scripts</li>
            <li>Marketing messages about our services and products</li>
            <li>Follow-up communications related to your use of the tool</li>
          </ul>
          <p className="mt-2">
            Message frequency varies. Standard message and data rates may apply. You can opt out at any time by replying STOP to any message or contacting us at <a href="mailto:hello@salesfu.ai" className="underline hover:text-zinc-900 dark:hover:text-zinc-100">hello@salesfu.ai</a>. We do not sell your phone number to third parties.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">6. Chat Data and Owner Access</h2>
          <p className="mt-2">
            By using this Service, you acknowledge and agree that all chat messages, generated scripts, and session data you create are stored in our database and may be accessed by the owner and operators of this application. This access is used to improve the tool, monitor usage patterns, and develop insights about vertical markets. Your conversations are not private from the application owner.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">7. Data Retention</h2>
          <p className="mt-2">
            We retain your session data, including all messages and generated scripts, indefinitely unless you request deletion. You may request deletion of your data by contacting us at <a href="mailto:hello@salesfu.ai" className="underline hover:text-zinc-900 dark:hover:text-zinc-100">hello@salesfu.ai</a>.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">8. Generated Content</h2>
          <p className="mt-2">
            Value offers and scripts generated by the Service are provided for your use. You are responsible for reviewing and adapting any generated content for your specific circumstances. We make no guarantees about the effectiveness, accuracy, or compliance of generated scripts. You retain ownership of the content you input; the generated output may be used by you at your discretion.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">9. Acceptable Use</h2>
          <p className="mt-2">
            You agree not to use the Service to generate content that is unlawful, deceptive, defamatory, or harmful. You are responsible for ensuring that any outbound calling scripts you use comply with applicable telemarketing laws and regulations, including the Telephone Consumer Protection Act (TCPA), Do Not Call (DNC) rules, and equivalent laws in your jurisdiction. You must not use the Service to harass, spam, or contact individuals who have not consented to be contacted.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">10. Intellectual Property</h2>
          <p className="mt-2">
            The Service, its design, logos, and underlying technology are the property of SalesFu AI Pty Ltd. You may not copy, modify, distribute, or create derivative works from the Service without our written permission. Your use of the Service does not grant you any intellectual property rights in the Service itself.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">11. No Warranty</h2>
          <p className="mt-2">
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranty of any kind, express or implied. We do not guarantee uptime, availability, or the quality of generated content. To the fullest extent permitted by law, we disclaim all warranties, including implied warranties of merchantability and fitness for a particular purpose.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">12. Limitation of Liability</h2>
          <p className="mt-2">
            To the fullest extent permitted by law, SalesFu AI Pty Ltd and its directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Service, even if we have been advised of the possibility of such damages.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">13. Indemnification</h2>
          <p className="mt-2">
            You agree to indemnify and hold harmless SalesFu AI Pty Ltd, its directors, employees, and agents from any claims, damages, losses, or expenses arising from your use of the Service or your violation of these Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">14. Changes to Terms</h2>
          <p className="mt-2">
            We may update these Terms at any time by posting the revised version on this page with an updated date. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms. We encourage you to review this page periodically.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">15. Governing Law</h2>
          <p className="mt-2">
            These Terms are governed by the laws of Queensland, Australia. Any disputes arising from these Terms or your use of the Service shall be resolved in the courts of Queensland, Australia.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">16. Contact</h2>
          <p className="mt-2">
            For questions about these Terms, to request data deletion, or for any other inquiries, contact us at <a href="mailto:hello@salesfu.ai" className="underline hover:text-zinc-900 dark:hover:text-zinc-100">hello@salesfu.ai</a>.
          </p>
        </section>
      </div>

      <div className="mt-10 rounded-lg border border-zinc-200 p-4 dark:border-zinc-700">
        <p className="text-sm text-zinc-600 dark:text-zinc-400">
          By creating an account or using the Service, you accept these Terms and Conditions. If you are verifying a phone number, you also consent to SMS communications as described in Section 5.
        </p>
        <div className="mt-3 flex gap-3">
          <Link href="/" className="text-sm font-medium text-zinc-900 hover:underline dark:text-zinc-100">Return to OfferFu</Link>
          <Link href="/privacy" className="text-sm font-medium text-zinc-500 hover:underline dark:text-zinc-400">Privacy Policy</Link>
        </div>
      </div>
    </div>
  );
}