import { auth, currentUser } from "@clerk/nextjs/server";
import { prisma } from "@/lib/db/prisma";
import { redirect } from "next/navigation";
import { AcceptTermsForm } from "./accept-terms-form";

export default async function TermsPage() {
  const { userId } = await auth();
  if (!userId) redirect("/");

  const dbUser = await prisma.user.findUnique({ where: { id: userId } });

  if (dbUser?.termsAcceptedAt && dbUser?.smsConsent) redirect("/");

  const user = await currentUser();
  const phone = user?.phoneNumbers?.[0]?.phoneNumber ?? null;
  const hasPhone = !!phone;
  const needsSmsConsent = hasPhone && !dbUser?.smsConsent;

  if (dbUser?.termsAcceptedAt && !needsSmsConsent) redirect("/");

  return (
    <div className="mx-auto max-w-2xl px-6 py-12">
      <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">
        Terms &amp; Conditions
      </h1>
      <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
        Last updated: June 18, 2026
      </p>

      <div className="mt-8 space-y-6 text-sm text-zinc-700 dark:text-zinc-300">
        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            1. Free Use
          </h2>
          <p className="mt-2">
            The Value Offer Generator is provided to you free of charge. You may
            use the tool to generate value offers and outbound call scripts for
            any vertical market at no cost.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            2. Chat Data and Owner Access
          </h2>
          <p className="mt-2">
            By using this tool, you acknowledge and agree that all chat messages,
            generated scripts, and session data you create are stored in our
            database and may be accessed by the owner and operators of this
            application. This access is used to improve the tool, monitor usage
            patterns, and develop insights about vertical markets. Your
            conversations are not private from the application owner.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            3. Data Retention
          </h2>
          <p className="mt-2">
            We retain your session data, including all messages and generated
            scripts, indefinitely unless you request deletion. You may request
            deletion of your data by contacting us.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            4. Generated Content
          </h2>
          <p className="mt-2">
            Value offers and scripts generated by the tool are provided for your
            use. You are responsible for reviewing and adapting any generated
            content for your specific circumstances. We make no guarantees about
            the effectiveness, accuracy, or compliance of generated scripts.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            5. Acceptable Use
          </h2>
          <p className="mt-2">
            You agree not to use the tool to generate content that is unlawful,
            deceptive, or harmful. You are responsible for ensuring that any
            outbound calling scripts you use comply with applicable telemarketing
            laws and regulations, including the TCPA and DNC rules in your
            jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            6. No Warranty
          </h2>
          <p className="mt-2">
            The tool is provided &ldquo;as is&rdquo; without warranty of any kind.
            We do not guarantee uptime, availability, or the quality of generated
            content.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            7. Changes
          </h2>
          <p className="mt-2">
            We may update these terms at any time. Continued use after changes
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            8. Contact
          </h2>
          <p className="mt-2">
            For questions about these terms or to request data deletion, contact
            the application owner.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">
            9. SMS Communications
          </h2>
          <p className="mt-2">
            By providing your phone number and checking the SMS consent box below, you agree to receive text messages from OfferFu. These may include:
          </p>
          <ul className="mt-2 ml-4 list-disc space-y-1">
            <li>Verification codes for account security</li>
            <li>Notifications about your generated scripts</li>
            <li>Marketing messages about our services and products</li>
            <li>Follow-up communications related to your use of the tool</li>
          </ul>
          <p className="mt-2">
            Message frequency varies. Standard message and data rates may apply. You can opt out at any time by replying STOP to any message or contacting us. We do not sell your phone number to third parties.
          </p>
        </section>
      </div>

      <div className="mt-10 rounded-lg border border-zinc-200 bg-amber-50 p-4 dark:border-zinc-700 dark:bg-amber-950">
        <p className="text-sm font-medium text-amber-800 dark:text-amber-200">
          Important: By accepting these terms, you acknowledge that the
          application owner can read all your chat messages and generated scripts.
          {needsSmsConsent && " You also consent to receiving SMS messages from OfferFu."}
        </p>
      </div>

      <AcceptTermsForm hasPhone={hasPhone} needsSmsConsent={needsSmsConsent} phone={phone} />
    </div>
  );
}